### ISSUE TITLE
Integration with ElevenlabsAPI: Voices sound different over API than on website

### ISSUE THREAD

**Issue by HackXIt** [inclusion-international/speech-jokey#5]
> We actually managed to do a bit of stuff in the last weeks. But we came across some problems... The current working state, that Natascha has now already to test, is the version on branch 'develop_breaks'. We managed to integrate the ElevenlabsAPI, synthesize an audio file and play it. And we made a new button, where you can choose a voice. However, if we generate an Audio, the voices don't sound like they do on the ElevenLabs Website.. Espacially the male voices are not male, but female in a lower tone... Did you have that problem in the old version as well? Or do you maybe have an idea what went wrong?😅

Relevant commit: 846b93a

**Comment by HackXIt** [comment]
my initial assumption would be that indeed APIs can change and also behave differently than what the provider puts on their website.

You need to keep in mind that the ElevenLabs Machine Learning Model is HEAVILY influenced by what is actually written in the text.

It is a generative model, so there is not much determinism when using it, albeit at the potential of much better & refined output.

**Comment by deinhofer** [comment]
fixed in #13 and #14
